# Module: NumPy Assignments



### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [4]:
import numpy as np

In [16]:
arr = np.random.randint(1,21,(5,5))

In [17]:
arr


array([[18, 10, 15,  6, 18],
       [13,  9, 14,  5, 15],
       [ 5, 15, 19,  1, 20],
       [18, 15,  1, 14,  9],
       [ 4,  5, 20,  9,  6]])

In [18]:
arr[:,2] = 1

In [41]:
arr


array([[18, 10,  1,  6, 18],
       [13,  9,  1,  5, 15],
       [ 5, 15,  1,  1, 20],
       [18, 15,  1, 14,  9],
       [ 4,  5,  1,  9,  6]])

In [45]:
arr1 = np.random.randint(1,16,(4,4))

In [50]:
np.fill_diagonal(arr,0)
arr

array([[ 0, 10,  1,  6, 18],
       [13,  0,  1,  5, 15],
       [ 5, 15,  0,  1, 20],
       [18, 15,  1,  0,  9],
       [ 4,  5,  1,  9,  0]])

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [51]:
arr2 = np.random.randint(1,36,(6,6))

In [52]:
arr2

array([[ 5, 30,  7, 31,  3,  3],
       [ 4, 28, 35, 35,  1, 14],
       [11, 31, 14, 22, 23, 23],
       [20, 23, 24,  4, 32, 25],
       [ 3,  1, 16, 25, 32, 12],
       [ 8, 24, 18, 35, 35, 11]])

In [55]:
arr2[2:5, 1:4]

array([[31, 14, 22],
       [23, 24,  4],
       [ 1, 16, 25]])

In [56]:
arr3 = np.random.randint(1,20,(5,5))

In [57]:
arr3

array([[19, 14, 12,  6,  6],
       [ 8, 16, 16,  5,  1],
       [ 5,  8,  7, 11, 16],
       [12,  7, 12, 19, 15],
       [ 9,  4,  4,  9,  8]])

In [70]:
arr3[1:-1,-1]

array([ 1, 16, 15])

In [60]:
border_elements = np.concatenate((arr3[0, :], arr3[-1, :], arr3[1:-1, 0], arr3[1:-1, -1]))
print("Border elements:")
print(border_elements)

Border elements:
[19 14 12  6  6  9  4  4  9  8  8  5 12  1 16 15]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [76]:
arr4 = np.random.randint(1,20,(3,4))
arr5 = np.random.randint(1,20,(3,4))

In [78]:
arr4+arr5

array([[26, 12, 18,  7],
       [18, 27, 26, 31],
       [22, 20, 18, 19]])

In [82]:
arr6 = np.random.randint(1,20,(4,4))
arr6

array([[13,  2, 15,  8],
       [14, 12,  6, 10],
       [15,  1, 16,  2],
       [ 3, 13,  7, 12]])

In [85]:
row_sum = np.sum(arr6,axis=1)
row_sum

array([38, 42, 34, 35])

In [87]:
col_sum = np.sum(arr6,axis=0)
col_sum

array([45, 28, 44, 32])