In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])
arr1.reshape(1,5)


array([[1, 2, 3, 4, 5]])

In [3]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [4]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
#vectorized 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [7]:
#statistical concepts - nomalization
data = np.array([1,2,3,4,5])

mean = np.mean(data)
std = np.std(data)

normalized_data = (data-mean)/std
print("normalized data: ", normalized_data)

normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [8]:
#logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>5) & (data<=8)]

array([6, 7, 8])